Reverted hook

diff --git a/templates/default/git/pre-commit b/templates/default/git/pre-commit
--- a/templates/default/git/pre-commit
+++ b/templates/default/git/pre-commit
@@ -1,17 +1,70 @@
 #!/bin/bash -ex
 
-DIRNAME="$(dirname -- "$0")"
-HOOKS="<%= node[:boilerplate_php][:git][:hooks] %>"
+PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
 
-for HOOK in $HOOKS
+echo "Checking PHP Lint..."
+FILES=""
+for FILE in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\\\.\(php\|ctp\)\$`
 do
-  echo "Running hook: $HOOK"
-  if [ -f "$DIRNAME/$HOOK" ]; then
-    "$DIRNAME/$HOOK" || exit $?
-  else
-    echo "Error: file $HOOK not found."
-    exit 1
-  fi
+	php -l -d display_errors=0 $PROJECT/$FILE
+	if [ $? != 0 ]
+	then
+		echo "Fix the parse error before commit."
+		exit 1
+	fi
+	FILES="$FILES $PROJECT/$FILE"
 done
+FILES_CSV=`echo $FILES | sed 's/\s/,/g'`
 
-exit 0
+if [ "$FILES" != "" ]
+then
+	echo "Running phpcs..."
+	phpcs --extensions=php --standard=CakePHP --encoding=utf-8 $FILES
+	if [ $? != 0 ]
+	then
+		echo "Fix the coding standard violations before commit."
+		exit 1
+	fi
+fi
+
+if [ "$FILES_CSV" != "" ]
+then
+	echo -n "Running phpmd..."
+	phpmd $FILES_CSV text ruleset/phpmd.xml
+	if [ $? != 0 ]
+	then
+		echo "Fix the coding standard violations before commit."
+		exit 1
+	fi
+fi
+
+if [ "$FILES" != "" ]
+then
+	echo "Running phpunit..."
+	for TEST in `git diff --cached --name-only --diff-filter=ACMR HEAD | egrep \\Test\\.\(php\)\$ | sed 's/app\/Test\/Case\/\([a-zA-Z0-9\/]\+\)Test\.php/\1/g'`
+	do
+		./lib/Cake/Console/cake test app $TEST --stderr --configuration phpunit.xml.dist
+		if [ $? != 0 ]
+		then
+			echo "Fix the test error before commit."
+			exit 1
+		fi
+	done
+fi
+
+exit $?
+# DIRNAME="$(dirname -- "$0")"
+# HOOKS="<%= node[:boilerplate_php][:git][:hooks] %>"
+
+# for HOOK in $HOOKS
+# do
+#   echo "Running hook: $HOOK"
+#   if [ -f "$DIRNAME/$HOOK" ]; then
+#     "$DIRNAME/$HOOK" || exit $?
+#   else
+#     echo "Error: file $HOOK not found."
+#     exit 1
+#   fi
+# done
+
+# exit 0
